package ProjectEuler;

public class Problem2 {

	/**
	 * @param args
	 *  Each new term in the Fibonacci sequence is generated by adding the previous two terms.
	 *  By starting with 1 and 2, the first 10 terms will be:
	 *  1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
	 *  By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
	 *  find the sum of the even-valued terms.
	 */
	public static void main(String[] args) {
		int total = 0;
//		int sum = 1;
//		int max = 4000000;
		// For each number check to see whether it is the sum of the previous two numbers.
		// If yes, then add it to an array named fibSeq
		int [] fibSeq;
		fibSeq = new int[35];
		fibSeq[0] = 1;
		fibSeq[1] = 2;
		
		for (int i = 2; i < 32; i++){
			fibSeq[i] = fibSeq[i-2] + fibSeq[i-1];
			System.out.println("fibSeq["+i+"] is "+fibSeq[i]);
			if (fibSeq[i] % 2 == 0){
				total += fibSeq[i];
			}
		}
		System.out.println("Total is = "+total);
	}
}